const String moonDescr =
    "Il lunare vive nell\’eco del Cancro Leopardi che scrisse proprio alla Luna una delle sue liriche più belle. "
    "\”Io venia pien d\’angoscia a rimirarti\”, verseggiò il poeta dall\’ombra scostante e malinconica. Come il solare ha bisogno della platea per emergere, "
    "così il lunare necessita del buio nelle sue ridondanze di silenzio e nostalgia per risplendere. "
    "Il lunare non è un plutonico incantatore di serpenti, né un mercuriale battutista, né un venusiano che si fa notare alle feste"
    " perché è bello e divertente. No, il lunare passa inosservato nei contesti di sfarzo e luce, o nella quotidianità rissosa, veloce e pragmatica."
    " È nell\’intimità di un sentimento, di un luogo, di un desiderio che il lunare si mette in mostra. La luna che vibra di luce riflessa non deve indurre"
    " a pensare al lunare come ad un soggetto senza personalità che rispecchia quella altrui. Il gioco di riflessi, nel caso del lunare, implica la "
    "capacità di accogliere e rimandare amplificato quel che si riceve: non per nulla la Luna è il primo pianeta femminile.  Il lunare ha quindi un\’attitudine contenitiva, "
    "flessibile, capace di adattarsi a ciò che intercetta. Se è donna potrà avere spiccate attitudini romantiche e materne verso chiunque, anche se non ha figli,"
    " con il desiderio immediato di proteggere ciò che percepisce fragile e bisognoso di sostegno. Se è uomo non metterà certamente in mostra i muscoli, ma la tenerezza, "
    "la dolcezza, la gentilezza dei modi. Sarà molto più micio che macho, per usare un\’espressione odierna. Sarà quello che resta quando tutti se ne vanno,"
    "a spettacolo finito. E mentre il solare, dopo gli applausi, non saprà più che fare, il lunare riuscirà a stupire"
    ". Entrambi i sessi condividono una profonda sensibilità. Nel caso del lunare, infatti, parlare di intelligenza, forse, "
    "è improprio: bisognerebbe parlare di intuizione, di un qualcosa che parte della pancia e arriva al cuore. "
    "Il cervello, in realtà, c\’entra sempre molto poco nei processi psichici caratteristici dei lunari."
    " La sua anima è d\’artista un po\’ come per il nettuniano: sia che sviluppi propensioni creative, sia che rimanga"
    " un sognatore, il suo sentire sarà comunque sempre un po\’ fuori dalla norma. Come fuori dalla norma saranno i suoi"
    " umori ballerini, i capricci, le impuntature, i silenzi, perché alla stregua del suo astro dominante, il lunare "
    "va a fasi e può variare improvvisamente umore senza motivi apparenti. Spesso a cambiarlo dentro sono moti interiori,"
    " ricordi fulminanti, passaggi nostalgici, rancori che emergono dal passato, perché in lui il passato è la dimensione preponderante."
    " Può vivere un torto di vent\’anni fa come se fosse accaduto due ore prima e un amore perduto di gioventù "
    "come il più grande della sua vita anche se ad oggi è felicemente sposato. Paga pegno alla sua grande memoria"
    " a cui sembra non sfuggire veramente nulla sia in termini di atmosfere, che di date, o volti. In questo è molto "
    "diverso dal nettuniano senza tempo che vive in un eterno presente. Proprio per queste qualità può essere molto "
    "affascinato dalla storia, dall\’archeologia, dallo studio delle cosiddette lingue morte. "
    "Può approfondire studi legati a saperi antichi come l\’alchimia, ma anche altri più moderni come la psicoanalisi "
    "perché l\’idea di scavare in una dimensione come l\’inconscio relegata ad un passato senza memoria costituisce per "
    "lui una sfida. In genere scrive bene, ha una mente narrativa ed è proprio la sua capacità di creare "
    "storie intorno ai fatti che vive che gli consente di fissarli così bene nella sua testa. Molti scrittori celebri, "
    "anche se non esplicitamente lunari, appartengono comunque al segno del Cancro.";
